[package]
name = "rooted"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parsr = "0.1.3"
roped = "0.6.0"
dirs = "5.0.1"